# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_role.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='account_role.proto',
  package='',
  serialized_pb='\n\x12\x61\x63\x63ount_role.proto\"8\n\x0blogin_proto\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x02(\t\x12\x13\n\x0b\x61\x63\x63ount_pwd\x18\x02 \x02(\t\"4\n\x0flogin_res_proto\x12\x10\n\x08\x65rror_id\x18\x01 \x02(\x05\x12\x0f\n\x07hoyo_id\x18\x02 \x01(\x05\"5\n\x0e\x63reate_account\x12\x11\n\tuser_name\x18\x01 \x02(\t\x12\x10\n\x08user_pwd\x18\x02 \x02(\t\"7\n\x12\x63reate_account_res\x12\x10\n\x08\x65rror_id\x18\x01 \x02(\x05\x12\x0f\n\x07hoyo_id\x18\x02 \x01(\x05\"2\n\x10join_world_proto\x12\x0b\n\x03pid\x18\x01 \x02(\x05\x12\x11\n\tserver_id\x18\x02 \x02(\x05\"V\n\x11\x63reate_role_proto\x12\x0f\n\x07hoyo_id\x18\x01 \x02(\x05\x12\x11\n\tserver_id\x18\x02 \x02(\x05\x12\x0f\n\x07hero_id\x18\x03 \x02(\x05\x12\x0c\n\x04name\x18\x04 \x02(\t\"5\n\x0frole_list_proto\x12\x0f\n\x07hoyo_id\x18\x01 \x02(\x05\x12\x11\n\tserver_id\x18\x02 \x02(\x05\":\n\x13role_list_res_proto\x12\x10\n\x08\x65rror_id\x18\x01 \x02(\x05\x12\x11\n\tplayer_id\x18\x02 \x01(\x05')




_LOGIN_PROTO = _descriptor.Descriptor(
  name='login_proto',
  full_name='login_proto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='login_proto.account_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_pwd', full_name='login_proto.account_pwd', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=78,
)


_LOGIN_RES_PROTO = _descriptor.Descriptor(
  name='login_res_proto',
  full_name='login_res_proto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_id', full_name='login_res_proto.error_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hoyo_id', full_name='login_res_proto.hoyo_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=80,
  serialized_end=132,
)


_CREATE_ACCOUNT = _descriptor.Descriptor(
  name='create_account',
  full_name='create_account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='create_account.user_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_pwd', full_name='create_account.user_pwd', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=187,
)


_CREATE_ACCOUNT_RES = _descriptor.Descriptor(
  name='create_account_res',
  full_name='create_account_res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_id', full_name='create_account_res.error_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hoyo_id', full_name='create_account_res.hoyo_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=189,
  serialized_end=244,
)


_JOIN_WORLD_PROTO = _descriptor.Descriptor(
  name='join_world_proto',
  full_name='join_world_proto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='join_world_proto.pid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_id', full_name='join_world_proto.server_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=246,
  serialized_end=296,
)


_CREATE_ROLE_PROTO = _descriptor.Descriptor(
  name='create_role_proto',
  full_name='create_role_proto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hoyo_id', full_name='create_role_proto.hoyo_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_id', full_name='create_role_proto.server_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero_id', full_name='create_role_proto.hero_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='create_role_proto.name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=298,
  serialized_end=384,
)


_ROLE_LIST_PROTO = _descriptor.Descriptor(
  name='role_list_proto',
  full_name='role_list_proto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hoyo_id', full_name='role_list_proto.hoyo_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_id', full_name='role_list_proto.server_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=386,
  serialized_end=439,
)


_ROLE_LIST_RES_PROTO = _descriptor.Descriptor(
  name='role_list_res_proto',
  full_name='role_list_res_proto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_id', full_name='role_list_res_proto.error_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='role_list_res_proto.player_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=441,
  serialized_end=499,
)

DESCRIPTOR.message_types_by_name['login_proto'] = _LOGIN_PROTO
DESCRIPTOR.message_types_by_name['login_res_proto'] = _LOGIN_RES_PROTO
DESCRIPTOR.message_types_by_name['create_account'] = _CREATE_ACCOUNT
DESCRIPTOR.message_types_by_name['create_account_res'] = _CREATE_ACCOUNT_RES
DESCRIPTOR.message_types_by_name['join_world_proto'] = _JOIN_WORLD_PROTO
DESCRIPTOR.message_types_by_name['create_role_proto'] = _CREATE_ROLE_PROTO
DESCRIPTOR.message_types_by_name['role_list_proto'] = _ROLE_LIST_PROTO
DESCRIPTOR.message_types_by_name['role_list_res_proto'] = _ROLE_LIST_RES_PROTO

class login_proto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN_PROTO

  # @@protoc_insertion_point(class_scope:login_proto)

class login_res_proto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN_RES_PROTO

  # @@protoc_insertion_point(class_scope:login_res_proto)

class create_account(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATE_ACCOUNT

  # @@protoc_insertion_point(class_scope:create_account)

class create_account_res(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATE_ACCOUNT_RES

  # @@protoc_insertion_point(class_scope:create_account_res)

class join_world_proto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOIN_WORLD_PROTO

  # @@protoc_insertion_point(class_scope:join_world_proto)

class create_role_proto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATE_ROLE_PROTO

  # @@protoc_insertion_point(class_scope:create_role_proto)

class role_list_proto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROLE_LIST_PROTO

  # @@protoc_insertion_point(class_scope:role_list_proto)

class role_list_res_proto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROLE_LIST_RES_PROTO

  # @@protoc_insertion_point(class_scope:role_list_res_proto)


# @@protoc_insertion_point(module_scope)
